[package]
name = "stackchan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
framebuffer = []

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
cpal = "0.15.3"
embedded-graphics = "0.8.1"
embedded-graphics-core = "0.4.0"
embedded-graphics-simulator = "0.6.0"
env_logger = "0.11.3"
evdev = { version = "0.12.2", features = ["tokio"] }
framebuffer = "0.3.1"
hound = "3.5.1"
log = { version = "0.4.22", features = ["std"] }
m5stack-avatar-rs = { version = "0.1.0", path = "m5stack-avatar-rs", features = ["std"] }
nb = "1.1.0"
nnnoiseless = "0.5.1"
openai-api-rs = "5.0.0"
rand = "0.8.5"
rodio = "0.19.0"
scs-servo = { path = "./scs-servo-rs/scs-servo", features = ["std"] }
serialport = { version = "4.4.0", default-features = false }
stackchan-rs = { version = "0.1.0", path = "stackchan-rs" }
tokio = { version = "1.38.0", features = ["full"] }
tokio-macros = "2.3.0"
#webrtc-audio-processing = { version = "0.4.0", features = ["bundled"] }
webrtc-vad = "0.4.0"
